# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComputeAlphaBeta <- function(y, x, WW, weight, Z, G) {
    .Call(`_bartik_weight_ComputeAlphaBeta`, y, x, WW, weight, Z, G)
}

